# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Category.all.destroy_all
Service.all.destroy_all

# array_of_categories = Category.create([{name: "Occupational Therapy", description: "Occupational therapy (OT) helps people who struggle to do everyday tasks because of poor motor skills. For kids, that includes tasks that are part of learning and functioning well at school.", image: "https://cdn.clipart.email/015c5884bd00465043ad7d99bcf17e24_best-occupational-therapist-illustrations-royalty-free-vector-_612-612.jpeg"}, {name: "Physical Therapy", description: " Physical therapy (PT) helps people work on their mobility skills, this may include, strengthening exercises or stretching exercises.", image: "https://cdn.clipart.email/0a6df96553d625e918852595f4f12646_pediatric-physical-therapy-illustrations-royalty-free-vector-_612-612.jpeg"}, {name: "Speech Therapy", description: "Speech therapy is an intervention service that focuses on improving a child's speech and abilities to understand and express language, including nonverbal language.", image:"https://www.clipartkey.com/mpngs/m/40-405548_stop-clipart-speech-therapy-cartoon.png"}])


category1 = Category.create(name: "Occupational Therapy", description: "Occupational therapy (OT) helps people who struggle to do everyday tasks because of poor motor skills. For kids, that includes tasks that are part of learning and functioning well at school.", image: "https://cdn.clipart.email/015c5884bd00465043ad7d99bcf17e24_best-occupational-therapist-illustrations-royalty-free-vector-_612-612.jpeg")

category2 = Category.create(name: "Physical Therapy", description: " Physical therapy (PT) helps people work on their mobility skills, this may include, strengthening exercises or stretching exercises.", image: "https://cdn.clipart.email/0a6df96553d625e918852595f4f12646_pediatric-physical-therapy-illustrations-royalty-free-vector-_612-612.jpeg")

category3 = Category.create(name: "Speech Therapy", description: "Speech therapy is an intervention service that focuses on improving a child's speech and abilities to understand and express language, including nonverbal language.", image:"https://www.clipartkey.com/mpngs/m/40-405548_stop-clipart-speech-therapy-cartoon.png")

Service.create([{name: "Therapy Kinections LLC", location:"Southbury, CT", phone_number: "(203)262-9909", url: "https://therapykinections.com/", category_id: category1.id}, {name: "Cheryl Weber, OTR", location:"Woodbridge, CT", phone_number: "(203) 901-4241", url: "http://www.pediatrictherapyservices.net/", category_id: category1.id}, {name: "Swim Angelfish", location:"Botsford, CT", phone_number: "(203) 545-0024", url: "https://swimangelfish.com/", category_id: category1.id}, {name: "Cheshire Fitness Zone", location:"Cheshire, CT", phone_number: "(203) 250-9663", url: "https://www.cheshirefitnesszone.com/", category_id: category1.id}, {name: "Swim Angelfish", location:"Botsford, CT", phone_number: "(203) 545-0024", url: "https://swimangelfish.com/", category_id: category2.id}, {name: "Cheshire Fitness Zone", location:"Cheshire, CT", phone_number: "(203) 250-9663", url: "https://www.cheshirefitnesszone.com/", category_id: category2.id},{name: "Ivy Rehab Physical Therapy", location:"Waterbury, CT", phone_number: "(203) 754-2266", url: "https://www.ivyrehab.com/pediatric/pediatric-physical-therapy/", category_id: category2.id}, {name: "Select Physical Therapy", location:"Watertown, CT", phone_number: "(860) 274-7573", url: "https://www.selectphysicaltherapy.com/services/", category_id: category2.id}, {name: "Therapy Kinections LLC", location:"Southbury, CT", phone_number: "(203)262-9909", url: "https://therapykinections.com/", category_id: category3.id},{name: "Cheshire Fitness Zone", location:"Cheshire, CT", phone_number: "(203) 250-9663", url: "https://www.cheshirefitnesszone.com/", category_id: category3.id},{name: "King's Speech and Learning", location:"Weatogue, CT", phone_number: "(860) 217-0098", url: "http://kingsspeechandlearning.com/wp/", category_id: category3.id}, {name: "Connec-to-Talk, LLC", location:"Wilton, CT", phone_number: "(203) 210-7124", url: "https://connec-to-talk.com/index-services#speech", category_id: category3.id}, {name: "Speech Path, LLC", location:"Farmington, CT", phone_number: "(860) 866-1817", url: "https://www.speechpathslp.com/", category_id: category3.id}])